name: Update Version

on:
  push:
    branches:
      - main
    paths-ignore:
      - "version"

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Update Version
        run: |
          current_version=$(cat version)
          new_version=$((current_version + 1))
          echo $new_version > version

      - name: Commit
        run: |
          git config user.email "github-actions[bot]@github.com"
          git config user.name "github-actions[bot]"
          git add version
          git commit -m "Update version number [automatically]"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
